"""Remove what an e2e run created, found by its run stamp.

    uv run python dev/e2e_cleanup.py STAMP            # show what would go
    uv run python dev/e2e_cleanup.py STAMP --apply    # remove it
    E2E_TARGET=live uv run python dev/e2e_cleanup.py STAMP --apply

Only documents whose name contains the stamp and that the server generated (tagged mcp-generated), plus the
local promotion folder 'E2E Promoted <stamp>', are touched. For them: processor filters on the pipelines are
deleted, streams in the feeds are marked deleted (Stroom's own retention removes the data), then the documents
and folders are deleted. Anything else whose name matches is listed and left alone.
"""
import asyncio
import sys
from types import SimpleNamespace
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / 'dev'))

import e2e_phase2 as p2  # noqa: E402
from security.guard import GENERATED, guard_from  # noqa: E402
from utils.stroom import StroomGateway  # noqa: E402


async def main(stamp: str, apply: bool):
    if len(stamp) < 6:
        raise SystemExit('Give the full run stamp (RUN STAMP ... in the e2e output)')
    stroom = StroomGateway(p2.target_settings())
    try:
        print(f"{'Removing' if apply else 'Would remove'} run {stamp} on "
              f"{stroom.settings.stroom_url if p2.LIVE else 'the local stack'}")
        found = (await stroom.find_documents(f'*{stamp}*', None, 1000)).get('values') or []
        ours, others = [], []
        for value in found:
            ref = value['docRef']
            if stamp not in (ref.get('name') or ''):
                continue
            node = await stroom.post('/explorer/v2/getFromDocRef', ref)
            generated = GENERATED in (node.get('tags') or [])
            promoted_folder = ref['type'] == 'Folder' and ref['name'] == f'E2E Promoted {stamp}'
            (ours if generated or promoted_folder else others).append({**ref, 'path': value.get('path')})
        for ref in others:
            print(f"  leave {ref['type']} '{ref['name']}' ({ref['path']}): not generated by the server")
        # The search index lags new documents, so also read the run's workspace folders from the explorer tree.
        guard = guard_from(SimpleNamespace(lifespan_context={'stroom': stroom}))
        workspace = stroom.settings.workspace_folder
        seen = {r['uuid'] for r in ours}
        for folder in [r for r in ours if r['type'] == 'Folder' and (r.get('path') or '').startswith(f'System/{workspace}')]:
            for doc in await guard.folder_contents(folder['name']):
                if doc['uuid'] not in seen and GENERATED in doc['tags']:
                    seen.add(doc['uuid'])
                    ours.append({k: doc[k] for k in ('type', 'uuid', 'name', 'path')})

        pipelines = {r['uuid'] for r in ours if r['type'] == 'Pipeline'}
        rows = (await stroom.post('/processorFilter/v1/find', {'expression': {'type': 'operator', 'op': 'AND',
                                                                             'children': []}})).get('values') or []
        filters = [r['processorFilter'] for r in rows if r.get('processorFilter')
                   and r['processorFilter'].get('pipelineUuid') in pipelines and not r['processorFilter'].get('deleted')]
        feeds = [r['name'] for r in ours if r['type'] == 'Feed']
        docs = [r for r in ours if r['type'] != 'Folder']
        folders = sorted((r for r in ours if r['type'] == 'Folder'), key=lambda r: -len(r.get('path') or ''))
        print(f"  {len(filters)} processor filter(s), streams in {len(feeds)} feed(s), {len(docs)} document(s), "
              f"{len(folders)} folder(s)")
        for ref in docs + folders:
            print(f"    {ref['type']:<14} {ref['name']}")
        if not apply:
            print('Dry run: nothing changed. Add --apply to remove.')
            return

        for f in filters:
            await stroom.request('DELETE', f"/processorFilter/v1/{f['id']}")
        marked = 0
        for feed in feeds:
            marked += await stroom.request('PUT', '/meta/v1/update/status', {
                'criteria': {'expression': {'type': 'operator', 'op': 'AND', 'children': [
                    {'type': 'term', 'field': 'Feed', 'condition': 'EQUALS', 'value': feed}]}},
                'currentStatus': None, 'newStatus': 'DELETED'}) or 0
        for group in (docs, folders):
            if group:
                await stroom.request('DELETE', '/explorer/v2/delete',
                                     {'docRefs': [{k: r[k] for k in ('type', 'uuid', 'name')} for r in group]})
        uuids = {r['uuid'] for r in ours}
        for _ in range(10):  # the search index takes a moment to drop deleted documents
            left = [v['docRef'] for v in (await stroom.find_documents(f'*{stamp}*', None, 1000)).get('values') or []
                    if v['docRef']['uuid'] in uuids]
            if not left:
                break
            await asyncio.sleep(3)
        print(f"Deleted {len(filters)} filter(s), marked {marked} stream(s) deleted, deleted {len(docs)} document(s) "
              f"and {len(folders)} folder(s); {len(left)} left" + (f": {[r['name'] for r in left]}" if left else ''))
    finally:
        await stroom.close()


if __name__ == '__main__':
    args = [a for a in sys.argv[1:] if a != '--apply']
    if len(args) != 1:
        raise SystemExit(__doc__)
    asyncio.run(main(args[0], '--apply' in sys.argv))
