{{- $rsKeys := and (not .Values.requestState.existingSecret) .Values.requestState.keys }}
{{- if $rsKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stroom-mcp.secretName" . }}
  labels:
    {{- include "stroom-mcp.labels" . | nindent 4 }}
type: Opaque
data:
  request-state-keys: {{ join "," $rsKeys | b64enc | quote }}
{{- end }}
