"""Generating translation code from a mapping, so the model does not have to write XSLT by hand."""
from typing import Annotated, Any

from fastmcp import Context
from fastmcp.exceptions import ToolError
from pydantic import Field

from tools.instructions import applicable_instructions
from utils.eventschema import EventSchema
from utils.params import ONE_OR_MORE
from utils.schemas import SchemaCache, event_logging_system_id
from utils.stroom import gateway_from
from tools.stepping import _outputs, _Pipeline
from pydantic import ValidationError

from utils.draftmap import draft_mapping
from utils.dsgen import EXAMPLES, SplitterSpec, dry_run, generate_splitter, infer_spec
from utils.samples import check_sample
from utils.localcheck import check_mapping, sample_records
from utils.profile import _inventory
from utils.refgen import ReferenceMapping, generate_reference
from utils.fielddoc import field_mapping_markdown, sampled_events
from utils.xsltgen import TranslationMapping, generate


async def event_schema(ctx: Context, version: str) -> EventSchema:
    schemas = ctx.lifespan_context.setdefault('event_schemas', {})
    if version not in schemas:
        cache = ctx.lifespan_context.setdefault('schemas', SchemaCache(gateway_from(ctx)))
        schemas[version] = EventSchema.parse(await cache.source(event_logging_system_id(version)))
    return schemas[version]


async def build_translation_xslt(
        ctx: Context,
        mapping: Annotated[TranslationMapping | dict[str, Any] | list[Any], Field(
            description="The translation mapping: {input, common: [{path, field|value|...}], events: [{name, when, fields}]}. "
                        "Start from draft_translation_mapping and edit it. A field inventory is not a mapping.")],
        schema_version: Annotated[str | None, Field(
            description="Event-logging version, e.g. '3.5.2'. Defaults to the configured version.")] = None,
        feeds: Annotated[list[str], ONE_OR_MORE, Field(description="Feeds the translation is for, so the standing "
                                                      "instructions for their folders are included.")] = [],
        pipeline_uuid: Annotated[str | None, Field(
            description="With stream_ids: step this pipeline with the generated XSLT over the sample (nothing is "
                        "saved), so field_mapping gives the TypeId and Description values the events actually get. "
                        "Do this before write_documentation.")] = None,
        stream_ids: Annotated[list[int], ONE_OR_MORE, Field(description="Sample streams to step for field_mapping.")] = [],
        max_records: Annotated[int, Field(ge=1, le=1000, description="Records to step for field_mapping.")] = 200,
        sample: Annotated[str | list[str] | None, Field(
            description="The raw sample, or a list of sample files, to check the mapping against before stepping: "
                        "fields no record has, and time formats the values do not fit. For data_splitter input "
                        "give splitter too.")] = None,
        splitter: Annotated[SplitterSpec | None, Field(
            description="The Data Splitter spec (build_data_splitter) that parses the sample, for the check.")] = None,
) -> dict[str, Any]:
    """
    Write the event-logging translation XSLT from a field mapping instead of by hand. Give the input kind
    (data_splitter, json or xml), fields every event shares (time, System, Device...), and one rule per
    kind of event with its conditions and fields. Text fields that hold several values (a message string with
    a time, user and action) are parsed with extract: a regular expression whose groups become fields; no
    substring-before/after chains. JSON held in a string is read with an xpath using json-to-xml(). Paths are
    checked against the schema: unknown paths come back with suggestions, constants are checked against
    allowed values, and elements are written in schema order with empty inputs left out. Fix any problems in the mapping and call again; then step_sample with
    draft_code={'<xslt element>': xslt}. Saves nothing. The standing instructions (AGENTS docs) that apply
    come back with the result: check the mapping follows them, and set mapping.style from any XSLT style
    section in them (naming, variables, xsl:maps). With pipeline_uuid and stream_ids it also returns
    field_mapping, the Field mapping section of the pipeline's documentation, to read before writing it; the
    saved doc's section is generated by write_documentation itself from the mapping kept with the XSLT
    (save_xslt mapping=...), stepped over the sample streams.
    """
    version = schema_version or gateway_from(ctx).settings.event_logging_version
    if not isinstance(mapping, TranslationMapping):
        try:
            mapping = TranslationMapping.model_validate(mapping)
        except ValidationError as e:
            problems = [f"{'.'.join(str(p) for p in x['loc'])}: {x['msg']}" for x in e.errors()[:4]]
            looks_like_inventory = isinstance(mapping, list) and mapping and all(isinstance(x, dict) and 'field' in x for x in mapping)
            if sample is not None:
                draft = draft_mapping(sample if isinstance(sample, list) else [sample])
                return {'status': 'needs_mapping', 'ok': False,
                        'problems': ["mapping is a list of fields, not a translation mapping" if looks_like_inventory else
                                     "mapping is not a translation mapping"] + problems,
                        'draft_mapping': draft['mapping'], 'splitter': draft['splitter'], 'notes': draft['notes'],
                        'hint': "Edit draft_mapping (the notes say what to decide) and call build_translation_xslt again "
                                "with it as mapping, the same sample, and the splitter if there is one."}
            raise ToolError("mapping is not a translation mapping: " + '; '.join(problems) + ". Get a starting one from "
                            "draft_translation_mapping(samples=the file texts) and edit it.") from e
    schema = await event_schema(ctx, version)
    result = generate(mapping, schema, version)
    result['schema_version'] = version
    if sample is not None:
        for text in (sample if isinstance(sample, list) else [sample]):
            check_sample(text)
        records, note = sample_records(mapping, sample, splitter)
        check = check_mapping(mapping, records)
        result['sample_check'] = {**check, **({'note': note} if note else {})}
        result['warnings'] += [f"sample: {w}" for w in check['warnings']]
        if check['problems']:
            # A time format no sample value fits fails every record at stepping: as good as a schema problem.
            result['problems'] += [f"sample: {p}" for p in check['problems']]
            result['ok'], result['xslt'] = False, None
    if mapping.input == 'json':
        result['pipeline_properties'] = {
            'jsonParser.addRootObject': mapping.json_layout == 'lines',
            'note': ("JSON lines need the parser's root map (addRootObject true, the default), which the XSLT "
                     "matches as /map/map." if mapping.json_layout == 'lines' else
                     "A JSON array is matched with or without the parser's root map; set addRootObject false on "
                     "create_pipeline to keep the output simple, as sibling pipelines do.") + " No text converter."}
    if result['ok'] and pipeline_uuid and stream_ids:
        stroom = gateway_from(ctx)
        pipeline = await _Pipeline.load(stroom, pipeline_uuid)
        element = pipeline.default_outputs()[0]
        # The documentation run steps a copy that marks each Event with its rule; the returned XSLT has no marks.
        marked = generate(mapping, schema, version, mark_rules=True)['xslt']
        outputs = await _outputs(stroom, pipeline, stream_ids, element, {element: marked}, max_records)
        events = sampled_events(list(outputs.values()))
        result['field_mapping'] = field_mapping_markdown(mapping, schema, events)
        result['field_mapping_sample'] = {'records': len(outputs), 'events': len(events), 'element': element}
        if not events:
            result['field_mapping_sample']['warning'] = ("The sample produced no events, so the event types table "
                                                         "has no values: check stream_ids are the pipeline's input.")
    elif result['ok']:
        # A table from the mapping alone would show how values are computed, not what they are; it was being
        # copied into documentation as it was. Only a sampled run gives one.
        result['field_mapping'] = None
        result['field_mapping_needs'] = ("pipeline_uuid and stream_ids: call again with the pipeline and its sample "
                                         "streams before write_documentation, for the values the events get.")
    result['hint'] = ("Fix the problems in the mapping (not the XSLT) and call again." if not result['ok'] else
                      "Step it: step_sample(pipeline, streams, draft_code={'translationFilter': xslt}) (use the "
                      "pipeline's XSLT element id). Fix issues in the mapping and regenerate; save with save_xslt, "
                      "passing this mapping as its `mapping`, so write_documentation can regenerate the Field mapping "
                      "section from it and later changes start from the mapping.")
    instructions = await applicable_instructions(ctx, feeds=feeds)
    if instructions['instructions']:
        result['standing_instructions'] = instructions['instructions']
        result['hint'] += " Check the mapping against standing_instructions (the most specific last)."
    return result


async def build_data_splitter(
        ctx: Context,
        sample: Annotated[str | None, Field(description="The raw sample text (every line of a file). The spec is "
                                                        "inferred from it when none is given, and run on it, so the "
                                                        "records and field names are seen before anything is created.")] = None,
        spec: Annotated[dict[str, Any] | None, Field(description=(
            "Only when the inferred spec is not right, or for free text: how a record divides into fields. "
            "{'kind': 'delimited', 'delimiter': ',', 'header': true} (or header: [names]); "
            "{'kind': 'key_value', 'delimiter': ' ', 'pair_separator': '=', 'quote': '\"'}; "
            "{'kind': 'regex', 'pattern': '^(\\S+) (.*)$', 'names': ['time', 'message']}; "
            "{'kind': 'syslog', 'rfc': 'rfc3164', 'body': {'kind': 'key_value'}}."))] = None,
) -> dict[str, Any]:
    """
    Write a Data Splitter (text converter) from the sample: its format is profiled (delimited with or without
    a header line, key=value pairs, syslog RFC 5424 or 3164 with the message parsed further) and the spec
    inferred, unless one is given; the spec is run on the sample locally and the records it produces, the lines
    that match nothing and the field names a mapping may use come back (give the same spec to
    build_translation_xslt as splitter). JSON and XML need no converter. Saves nothing: save_text_converter saves it.
    """
    if sample is None and spec is None:
        raise ToolError("Give the sample (the file's text): the spec is inferred from it")
    if sample is not None:
        check_sample(sample)
    profiled: dict[str, Any] | None = None
    if spec is None:
        inferred, profiled = infer_spec(sample)
        if inferred is None:
            fmt = profiled['format']
            if fmt in ('json array', 'json lines', 'xml', 'xml fragments'):
                raise ToolError(f"The sample is {fmt}: it needs no Data Splitter. {profiled.get('suggested_parser')}. "
                                f"Go on to build_translation_xslt (input {'json' if fmt.startswith('json') else fmt.replace(' ', '_')}).")
            raise ToolError(f"The sample's format could not be inferred ({fmt}): give spec, a regex with a name per group, e.g. "
                            f"{EXAMPLES['unknown text']}, written for lines like {profiled.get('examples', [''])[0]!r}")
        chosen = inferred
    else:
        try:
            chosen = SplitterSpec.model_validate(spec)
        except ValidationError as e:
            fmt = profile_format(sample) if sample else None
            example = EXAMPLES.get(fmt or '', EXAMPLES['delimited'])
            raise ToolError(f"spec is not a splitter spec ({'; '.join(x['msg'] for x in e.errors()[:3])}). For "
                            f"{fmt or 'this'} data it looks like {example}; or leave spec out and it is inferred from the sample.") from e
    result: dict[str, Any] = {'spec': chosen.model_dump(exclude_none=True, exclude_defaults=True),
                              'inferred': spec is None, 'converter': generate_splitter(chosen), 'converter_type': 'DATA_SPLITTER',
                              **({'format': profiled['format']} if profiled else {})}
    if sample is not None:
        run = dry_run(chosen, sample)
        result.update({'records': len(run['records']), 'fields': _inventory(run['records']),
                       'first_records': run['records'][:5], 'unmatched_lines': run['unmatched_lines'][:10],
                       'unmatched_count': len(run['unmatched_lines'])})
        if run['unmatched_lines'] and not run['records']:
            result['hint'] = "No line matched the spec: check the pattern or delimiter against the lines shown."
        elif run['unmatched_lines']:
            result['hint'] = (f"{len(run['unmatched_lines'])} line(s) match nothing and would produce no record: widen the "
                              f"spec, or confirm with the user that they are noise.")
        else:
            result['hint'] = ("Every line parsed. Use these field names in the mapping, with this spec as splitter; "
                              "save_text_converter saves the converter.")
    return result


def profile_format(sample: str) -> str:
    from utils.profile import profile
    return profile(sample)['format']


async def build_reference_xslt(
        ctx: Context,
        mapping: Annotated[ReferenceMapping, Field(description="The maps a reference feed provides: name, key field "
                                                               "and value fields per map.")],
        schema_version: Annotated[str | None, Field(description="reference-data schema version; defaults to the "
                                                                "newest this Stroom holds.")] = None,
) -> dict[str, Any]:
    """
    Write the XSLT of a reference-data pipeline (a child of the Reference Data template) from a mapping: for
    each record and map, a <reference> with the map name, key and value in reference-data:2. The events
    pipeline then names the feed as a pipeline reference and its mapping reads the map with lookup.
    """
    version = schema_version
    if not version:
        cache = ctx.lifespan_context.setdefault('schemas', SchemaCache(gateway_from(ctx)))
        ids = [s for s in await cache.system_ids() if 'reference-data' in s]
        version = ids[-1].split('-v')[-1].removesuffix('.xsd') if ids else '2.0.1'
    result = generate_reference(mapping, version)
    result['schema_version'] = version
    result['hint'] = ("Fix the problems and call again." if not result['ok'] else
                      "save_xslt it; create_pipeline from the Reference Data template (find_pipeline_templates "
                      "stage=reference) with combinedParser.textConverter (if the feed is text) and translationFilter.xslt; "
                      "create_processor_filter on the Raw Reference stream; wait_for_processing output_type='Reference'. "
                      "Then give the events pipeline references=[{feed, loader_pipeline}].")
    return result


async def draft_translation_mapping(
        ctx: Context,
        samples: Annotated[dict[str, str] | list[str] | str, Field(description="The sample files' text (every line), by "
                                                                            "file name or as a list; not paths.")],
        source_name: Annotated[str, Field(description="The source, e.g. 'FortiOS firewall': names the system and generator "
                                                      "until the user confirms them.")] = '',
        system_name: Annotated[str | None, Field(description="EventSource/System/Name, if the user has said.")] = None,
        environment: Annotated[str | None, Field(description="EventSource/System/Environment, if the user has said, e.g. Prod.")] = None,
) -> dict[str, Any]:
    """
    A starting translation mapping drafted from the sample, to edit rather than write from nothing: the input
    kind and layout from the profile, the obvious event-logging homes for fields by name (time with its
    pattern, host, client and server addresses and ports, user, event type, message), one rule per kind of
    event the naming field shows (Authenticate for logon and logoff kinds, Unknown with Data for the rest, to
    replace with the right action element), every other field carried as Data, and notes on what is left to
    decide. For text formats the Data Splitter spec comes with it. Then build_translation_xslt with the edited
    mapping, the sample and the splitter.
    """
    result = draft_mapping(samples, source_name, system_name, environment)
    version = gateway_from(ctx).settings.event_logging_version
    try:
        checked = generate(TranslationMapping.model_validate(result['mapping']), await event_schema(ctx, version), version)
        result['schema_check'] = {'ok': checked['ok'], 'problems': checked['problems'], 'warnings': checked['warnings'][:6]}
    except ToolError as e:
        result['schema_check'] = {'ok': None, 'note': str(e)}
    result['hint'] = ("Decide what the notes ask (the action element per kind of event, System Name and Environment, the "
                      "time zone), then build_translation_xslt(mapping=this mapping, sample=the texts, splitter=this splitter).")
    return result


ALL_TOOLS = [build_translation_xslt, build_data_splitter, build_reference_xslt, draft_translation_mapping]
