"""Generating translation code from a mapping, so the model does not have to write XSLT by hand."""
from typing import Annotated, Any

from fastmcp import Context
from pydantic import Field

from tools.instructions import applicable_instructions
from utils.eventschema import EventSchema
from utils.params import ONE_OR_MORE
from utils.schemas import SchemaCache, event_logging_system_id
from utils.stroom import gateway_from
from tools.stepping import _outputs, _Pipeline
from utils.dsgen import SplitterSpec, dry_run, generate_splitter
from utils.localcheck import check_mapping, sample_records
from utils.profile import _inventory
from utils.refgen import ReferenceMapping, generate_reference
from utils.fielddoc import field_mapping_markdown, sampled_events
from utils.xsltgen import TranslationMapping, generate


async def event_schema(ctx: Context, version: str) -> EventSchema:
    schemas = ctx.lifespan_context.setdefault('event_schemas', {})
    if version not in schemas:
        cache = ctx.lifespan_context.setdefault('schemas', SchemaCache(gateway_from(ctx)))
        schemas[version] = EventSchema.parse(await cache.source(event_logging_system_id(version)))
    return schemas[version]


async def build_translation_xslt(
        ctx: Context,
        mapping: Annotated[TranslationMapping, Field(description="Which input field or constant goes to which "
                                                                 "event-logging path, per kind of event.")],
        schema_version: Annotated[str | None, Field(
            description="Event-logging version, e.g. '3.5.2'. Defaults to the configured version.")] = None,
        feeds: Annotated[list[str], ONE_OR_MORE, Field(description="Feeds the translation is for, so the standing "
                                                      "instructions for their folders are included.")] = [],
        pipeline_uuid: Annotated[str | None, Field(
            description="With stream_ids: step this pipeline with the generated XSLT over the sample (nothing is "
                        "saved), so field_mapping gives the TypeId and Description values the events actually get. "
                        "Do this before write_documentation.")] = None,
        stream_ids: Annotated[list[int], ONE_OR_MORE, Field(description="Sample streams to step for field_mapping.")] = [],
        max_records: Annotated[int, Field(ge=1, le=1000, description="Records to step for field_mapping.")] = 200,
        sample: Annotated[str | list[str] | None, Field(
            description="The raw sample, or a list of sample files, to check the mapping against before stepping: "
                        "fields no record has, and time formats the values do not fit. For data_splitter input "
                        "give splitter too.")] = None,
        splitter: Annotated[SplitterSpec | None, Field(
            description="The Data Splitter spec (build_data_splitter) that parses the sample, for the check.")] = None,
) -> dict[str, Any]:
    """
    Write the event-logging translation XSLT from a field mapping instead of by hand. Give the input kind
    (data_splitter, json or xml), fields every event shares (time, System, Device...), and one rule per
    kind of event with its conditions and fields. Text fields that hold several values (a message string with
    a time, user and action) are parsed with extract: a regular expression whose groups become fields; no
    substring-before/after chains. JSON held in a string is read with an xpath using json-to-xml(). Paths are
    checked against the schema: unknown paths come back with suggestions, constants are checked against
    allowed values, and elements are written in schema order with empty inputs left out. Fix any problems in the mapping and call again; then step_sample with
    draft_code={'<xslt element>': xslt}. Saves nothing. The standing instructions (AGENTS docs) that apply
    come back with the result: check the mapping follows them, and set mapping.style from any XSLT style
    section in them (naming, variables, xsl:maps). With pipeline_uuid and stream_ids it also returns
    field_mapping, the Field mapping section of the pipeline's documentation, to read before writing it; the
    saved doc's section is generated by write_documentation itself from the mapping kept with the XSLT
    (create_xslt mapping=...), stepped over the sample streams.
    """
    version = schema_version or gateway_from(ctx).settings.event_logging_version
    schema = await event_schema(ctx, version)
    result = generate(mapping, schema, version)
    result['schema_version'] = version
    if sample is not None:
        records, note = sample_records(mapping, sample, splitter)
        check = check_mapping(mapping, records)
        result['sample_check'] = {**check, **({'note': note} if note else {})}
        result['warnings'] += [f"sample: {w}" for w in check['warnings']]
        if check['problems']:
            # A time format no sample value fits fails every record at stepping: as good as a schema problem.
            result['problems'] += [f"sample: {p}" for p in check['problems']]
            result['ok'], result['xslt'] = False, None
    if mapping.input == 'json':
        result['pipeline_properties'] = {
            'jsonParser.addRootObject': mapping.json_layout == 'lines',
            'note': ("JSON lines need the parser's root map (addRootObject true, the default), which the XSLT "
                     "matches as /map/map." if mapping.json_layout == 'lines' else
                     "A JSON array is matched with or without the parser's root map; set addRootObject false on "
                     "create_pipeline to keep the output simple, as sibling pipelines do.") + " No text converter."}
    if result['ok'] and pipeline_uuid and stream_ids:
        stroom = gateway_from(ctx)
        pipeline = await _Pipeline.load(stroom, pipeline_uuid)
        element = pipeline.default_outputs()[0]
        # The documentation run steps a copy that marks each Event with its rule; the returned XSLT has no marks.
        marked = generate(mapping, schema, version, mark_rules=True)['xslt']
        outputs = await _outputs(stroom, pipeline, stream_ids, element, {element: marked}, max_records)
        events = sampled_events(list(outputs.values()))
        result['field_mapping'] = field_mapping_markdown(mapping, schema, events)
        result['field_mapping_sample'] = {'records': len(outputs), 'events': len(events), 'element': element}
        if not events:
            result['field_mapping_sample']['warning'] = ("The sample produced no events, so the event types table "
                                                         "has no values: check stream_ids are the pipeline's input.")
    elif result['ok']:
        # A table from the mapping alone would show how values are computed, not what they are; it was being
        # copied into documentation as it was. Only a sampled run gives one.
        result['field_mapping'] = None
        result['field_mapping_needs'] = ("pipeline_uuid and stream_ids: call again with the pipeline and its sample "
                                         "streams before write_documentation, for the values the events get.")
    result['hint'] = ("Fix the problems in the mapping (not the XSLT) and call again." if not result['ok'] else
                      "Step it: step_sample(pipeline, streams, draft_code={'translationFilter': xslt}) (use the "
                      "pipeline's XSLT element id). Fix issues in the mapping and regenerate; save with create_xslt, "
                      "passing this mapping as its `mapping`, so write_documentation can regenerate the Field mapping "
                      "section from it and later changes start from the mapping.")
    instructions = await applicable_instructions(ctx, feeds=feeds)
    if instructions['instructions']:
        result['standing_instructions'] = instructions['instructions']
        result['hint'] += " Check the mapping against standing_instructions (the most specific last)."
    return result


async def build_data_splitter(
        ctx: Context,
        spec: Annotated[SplitterSpec, Field(description="How a record of the text divides into named fields.")],
        sample: Annotated[str | None, Field(description="The raw sample: the spec is run on it here, so the records "
                                                        "and field names are seen before anything is created.")] = None,
) -> dict[str, Any]:
    """
    Write a Data Splitter (text converter) from a spec instead of by hand: delimited columns with or without a
    header line, a regex with a name per group, key=value pairs, or syslog (RFC 5424 or 3164) with the
    message parsed further. With the sample, runs the spec locally and returns the records it produces, the
    lines that match nothing, and the field names a mapping may use (give the same spec to
    build_translation_xslt as splitter). Saves nothing: create_text_converter saves the converter.
    """
    result: dict[str, Any] = {'converter': generate_splitter(spec), 'converter_type': 'DATA_SPLITTER'}
    if sample is not None:
        run = dry_run(spec, sample)
        result.update({'records': len(run['records']), 'fields': _inventory(run['records']),
                       'first_records': run['records'][:5], 'unmatched_lines': run['unmatched_lines'][:10],
                       'unmatched_count': len(run['unmatched_lines'])})
        if run['unmatched_lines'] and not run['records']:
            result['hint'] = "No line matched the spec: check the pattern or delimiter against the lines shown."
        elif run['unmatched_lines']:
            result['hint'] = (f"{len(run['unmatched_lines'])} line(s) match nothing and would produce no record: widen the "
                              f"spec, or confirm with the user that they are noise.")
        else:
            result['hint'] = "Every line parsed. Use these field names in the mapping, with this spec as splitter."
    return result


async def build_reference_xslt(
        ctx: Context,
        mapping: Annotated[ReferenceMapping, Field(description="The maps a reference feed provides: name, key field "
                                                               "and value fields per map.")],
        schema_version: Annotated[str | None, Field(description="reference-data schema version; defaults to the "
                                                                "newest this Stroom holds.")] = None,
) -> dict[str, Any]:
    """
    Write the XSLT of a reference-data pipeline (a child of the Reference Data template) from a mapping: for
    each record and map, a <reference> with the map name, key and value in reference-data:2. The events
    pipeline then names the feed as a pipeline reference and its mapping reads the map with lookup.
    """
    version = schema_version
    if not version:
        cache = ctx.lifespan_context.setdefault('schemas', SchemaCache(gateway_from(ctx)))
        ids = [s for s in await cache.system_ids() if 'reference-data' in s]
        version = ids[-1].split('-v')[-1].removesuffix('.xsd') if ids else '2.0.1'
    result = generate_reference(mapping, version)
    result['schema_version'] = version
    result['hint'] = ("Fix the problems and call again." if not result['ok'] else
                      "create_xslt it; create_pipeline from the Reference Data template (find_pipeline_templates "
                      "stage=reference) with combinedParser.textConverter (if the feed is text) and translationFilter.xslt; "
                      "create_processor_filter on the Raw Reference stream; wait_for_processing output_type='Reference'. "
                      "Then give the events pipeline references=[{feed, loader_pipeline}].")
    return result


ALL_TOOLS = [build_translation_xslt, build_data_splitter, build_reference_xslt]
